apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: playlist-sharify-autoscaler
  namespace: playlist-sharify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playlist-sharify-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 25
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 7
